version: "3.8"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    # Add this healthcheck
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 30s  # Increase from 10s to 30s
      timeout: 10s   # Increase timeout
      retries: 3
      start_period: 60s  # Give more time for initial startup

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/social_reply_db2
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongo:27017/social_reply_db4
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    depends_on:
      mongo:
        condition: service_healthy
      api:
        condition: service_started
    command: ["streamlit", "run", "app/demo.py"]
    restart: unless-stopped

  init-db:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/social_reply_db4  # Match your init_db.py database name
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./scripts:/app/scripts
    command: bash -c "python scripts/init_db.py && python scripts/import_posts.py"
    profiles:
      - init

volumes:
  mongo_data: